### PR TITLE
Potential fix to repair categorized links (issue #8)

### PR DESCRIPTION
**Pull request by sleepy-manul**
Hi, I might have a fix for issue #8  - can you please take a look at it and verify that it works in your installations as well?

### CODE REVIEW

**Comment by gabloe** [comment]
It would be great if this could be reviewed and merged :)

**Comment by bvdriel** [comment]
anyone? we need this too. Are there no maintainers left?

**Comment by Lakhtenkov-iv** [comment]
Are there any update regarding this PR?

**Comment by smh** [comment]
@taksan Any hope of getting this merged?

**Comment by taksan** [comment]
Yes, I will take a look

**Comment by thommelutten** [comment]
Bump on this. Would be nice to have the fix merged in

**Comment by Lakhtenkov-iv** [comment]
I consider that same changes were merged in #15

**Comment by basil** [comment]
Closing in favor of #15 (released in [1.11](https://github.com/jenkinsci/categorized-view-plugin/releases/tag/categorized-view-1.11)).

**Pull request closed without merging**
