### PR TITLE
Update for new table design (Jenkins 2.332.1)

### PR DESCRIPTION
**Pull request by Zohhak**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

I updated the ListView to the new table design. I think it looks fine, but if you have any suggestions what color to use for the groups, iam happy for any suggestions. It works for both light and dark theme as of now.

test
test_light

What i did:
* updated the versions in the pom.xml (this time without the breaking api one :D)
* updated the jelly files to adopt the new table design
* updated the css files for better styling
* fixed breaking changes in the java classes with the new update

somehow i am not able to comment directly, so here my two findings as of now: font weight seemed off for nested <tr> and line between nested <tr> could be switched to the default one -> Fixed

### CODE REVIEW

**Comment by Jbekker** [comment]
@taksan, any change you could have a look at this?

**Comment by basil** [comment]
@jenkinsci/sig-ux Any thoughts on this?

**Comment by timja** [comment]
code looks sensible and screenshots look good, not run locally

**Comment by basil** [comment]
Closing in favor of #37

**Pull request closed without merging**
